### ISSUE TITLE
too many URLs are `null`

### ISSUE THREAD

**Issue by eldrin** [pizzicatomania/bootstrap_test#4]
사실상 거의 모든 프리뷰 URL이 `null` 로 들어온다 어떻게 된 것인가?

[가능성]

1. `unique_tracks.json` 에 애초에 제대로 등재되지 않았다
2. 추천 결과가 기가막히게 URL 없는 50프로만 가져온다

[해결책]

- 만약 `unique_tracks.json` 에 애초에 없다 -> 이 화일 업데이트
- 추천 결과가 기가막히게 없는 애들만 가져온다 -> 다른 플랫폼에서 URL search & crawl?

**Comment by eldrin** [comment]
필드명 미스매치로 데이터가 안들어가고 있었음

#5 에서 고침. 머지 기다리는 중

**Comment by pizzicatomania** [comment]
머지 완료
